spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:my_kanban}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
app.api.version=1.0.3
app.jwt.secret=change-this-secret-key-for-production-please-123456
app.jwt.expiration-minutes=120
app.seed.admin.enabled=${APP_SEED_ADMIN_ENABLED:true}
app.seed.admin.full-name=${APP_SEED_ADMIN_FULL_NAME:Tiago Admin}
app.seed.admin.email=${APP_SEED_ADMIN_EMAIL:tiago.r.c.sn@hotmail.com}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:mypassword}
